# Generated by Django 5.1.2 on 2024-10-21 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=30)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.department')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.job')),
            ],
        ),
    ]
